- name: OrangeFox Build Action
  # You may pin to the exact commit or the version.
  # uses: mlm-games/orangefox-builder-action@eac4f3391c67149b2c3cb0fa15ac74e0a69c0d70
  uses: mlm-games/orangefox-builder-action@v1.3
  with:
    # OrangeFox Manifest Branch
    MANIFEST_BRANCH: 12.1
    # Custom Recovery Tree
    DEVICE_TREE: https://github.com/bekirakil-0/android_device_samsung_r9s.git
    # Custom Recovery Tree Branch (use default branch if not specified)
    DEVICE_TREE_BRANCH: fox_14.1 
    # Specify your Device Codename (leave blank to auto-detect)
    DEVICE_NAME: r9s 
    # Specify your Device Path (leave blank to auto-detect from device tree)
    DEVICE_PATH: device/samsung/r9s 
    # Specify your Build Target
    BUILD_TARGET: recovery
