- name: 🦊 Orangefox Recovery Builder Action
  # You may pin to the exact commit or the version.
  # uses: UWU-TEAM/UWU-OrangeFox-Builder@6a4252972bd1b56de75ab55997f925abcc7d57c9
  uses: UWU-TEAM/UWU-OrangeFox-Builder@v1.0.0
  with:
    # Source On OrangeFox Recovery
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
    # Branch On Orangefox For Sync
    FOX_SYNC_BRANCH:  14.1
    # Name in GitHub Account
    USER_NAME: bekirakil-0 
    # E-mail in GitHub Account
    USER_EMAIL: akilbekir101@gmail.com 
    # Kernel Tree On Your Device
    KERNEL_TREE: # optional, default is 
    # Branch On Your Kernel Tree
    KERNEL_BRANCH: # optional, default is 
    # Path On Your Kernel Directory
    KERNEL_PATH: # optional, default is kernel/vivo/1938
    # OrangeFox Device Tree
    DEVICE_TREE: https://github.com/bekirakil-0/android_device_samsung_r9s.git
    # OrangeFox Device Tree Branch
    DEVICE_TREE_BRANCH: fox_14.1
    # Specify Your Device Path
    DEVICE_PATH: device/samsung/r9s
    # Specify Your Device Codename
    DEVICE_NAME: r9s
    # Specify Your Build Target [boot, recovery, vendorboot
    BUILD_TARGET: recovery
    # Common Tree On Your Device
    COMMON_TREE: # optional, default is 
    # Branch On Your Common Tree
    COMMON_BRANCH: # optional, default is 
    # Path On Your Common Directory
    COMMON_PATH: # optional, default is common/vivo/1938
    # Image size must be 192x192
    MAINTAINER_URL: # default is https://i.ibb.co.com/8gyjXq06/maintainer.png
    # Upload Build To Github Release
    GH_RELEASE: # default is true
    # Telegram Chat ID
    TG_CHAT_ID: # optional, default is 
    # Telegram Bot Token
    TG_TOKEN: # optional, default is 
