name: Build TWRP Recovery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP Recovery with Auto-Detection
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set Swap Space (Optional)
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 100

    - name: Build TWRP
      uses: mlm-games/twrp-build-action@main
      with:
        # MANIFEST_BRANCH is omitted to use the default branch
        DEVICE_TREE: 'https://github.com/mlm-games/device_manufacturer_codename'
        # DEVICE_TREE_BRANCH is omitted to use the default branch
        BUILD_TARGET: 'recovery'     # Options: 'recovery', 'boot', 'vendorboot'
        # DEVICE_NAME, DEVICE_PATH, and MAKEFILE_NAME are omitted to auto-detect

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-Recovery
        path: ${{ env.OUTPUT_DIR }}/*.img
